/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_macowu_jni_NdkJniUtils */

#ifndef _Included_com_test_macowu_jni_NdkJniUtils
#define _Included_com_test_macowu_jni_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_macowu_jni_NdkJniUtils
 * Method:    helloFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_macowu_jni_NdkJniUtils_helloFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_test_macowu_jni_NdkJniUtils
 * Method:    getDeviceInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_macowu_jni_NdkJniUtils_getDeviceInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
